#!/usr/bin/env node
var exec = require('child_process').exec

exec("npm -g root", function(err, stdout, stderr){
  if(err){
    console.log("!---Failed to find npm root directory!")
    process.exit(1)
  } else {
    module.paths.push(stdout.trim());
  }
  require("moov_builder")({browserSync: {port: 9099}}).safeStart();
});